# Generated by Django 5.1.6 on 2025-02-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('Water', 'Water'), ('Roads', 'Roads'), ('Internet', 'Internet'), ('Sanitation', 'Sanitation'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Public_Safety', 'Public Safety'), ('Housing', 'Housing'), ('Transportation', 'Transportation')], max_length=50),
        ),
    ]
