# Generated by Django 5.1.6 on 2025-02-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
